export const countries = {
  JPN: "Japan (JPN)",
  AUS: "Australia (AUS)",
  CAN: "Canada (CAN)",
  GBR: "Great Britain (GBR)",
  GER: "Germany (GER)",
  NED: "The Netherlands (NED)",
  RSA: "South Africa (RSA)",
  THA: "Thailand (THA)",
  USA: "United States of America (USA)",
  ALG: "Algeria (ALG)",
  ASA: "American Samoa (ASA)",
  AND: "Andorra (AND)",
  ANG: "Angola (ANG)",
  ANT: "Antigua (ANT)",
  ARG: "Argentina (ARG)",
  AUT: "Austria (AUT)",
  AZE: "Azerbaijan (AZE)",
  BAH: "Bahamas (BAH)",
  BRN: "Bahrain (BRN)",
  BAR: "Barbados (BAR)",
  BLR: "Belarus (BLR)",
  BEL: "Belgium (BEL)",
  BER: "Bermuda (BER)",
  BRA: "Brazil (BRA)",
  IVB: "British Virgin Islands (IVB)",
  BUL: "Bulgaria (BUL)",
  CAY: "Cayman Islands (CAY)",
  CHI: "Chile (CHI)",
  CHN: "China, PR (CHN)",
  TPE: "Chinese Taipei (TPE)",
  COL: "Columbia (COL)",
  COK: "Cook Islands (COK)",
  CRO: "Croatia (CRO)",
  CUB: "Cuba (CUB)",
  CYP: "Cyprus (CYP)",
  CZE: "Czech Republic (CZE)",
  DEN: "Denmark (DEN)",
  DOM: "Dominican Republic (DOM)",
  ECU: "Ecuador (ECU)",
  EGY: "Egypt (EGY)",
  ESA: "El Salvador (ESA)",
  EST: "Estonia (EST)",
  FIJ: "Fiji (FIJ)",
  FIN: "Finland (FIN)",
  FRA: "France (FRA)",
  MKD: "Macedonia (MKD)",
  GRE: "Greece (GRE)",
  GRN: "Grenada (GRN)",
  GUM: "Guam (GUM)",
  GUA: "Guatemala (GUA)",
  HKG: "Hong Kong (HKG)",
  HUN: "Hungary (HUN)",
  ISL: "Iceland (ISL)",
  IND: "India (IND)",
  INA: "Indonesia (INA)",
  IRL: "Ireland (IRL)",
  ISR: "Israel (ISR)",
  ITA: "Italy (ITA)",
  JAM: "Jamaica (JAM)",
  KAZ: "Kazakhstan (KAZ)",
  KEN: "Kenya (KEN)",
  KOR: "Korea (KOR)",
  KUW: "Kuwait (KUW)",
  LAT: "Latvia (LAT)",
  LIB: "Lebanon (LIB)",
  LBA: "Libya (LBA)",
  LIE: "Liechtenstein (LIE)",
  LTU: "Lithuania (LTU)",
  LUX: "Luxembourg (LUX)",
  MAS: "Malaysia (MAS)",
  MLT: "Malta (MLT)",
  MRI: "Maurititius (MRI)",
  MEX: "Mexico (MEX)",
  FSM: "Micronesia (FSM)",
  MDA: "Moldova (MDA)",
  MON: "Monaco (MON)",
  MAR: "Morocco (MAR)",
  MYA: "Myanmar (MYA)",
  NAM: "Namibia (NAM)",
  AHO: "Netherlands Antilles (AHO)",
  NZL: "New Zealand (NZL)",
  NOR: "Norway (NOR)",
  PAK: "Pakistan (PAK)",
  PNG: "Papua New Guinea (PNG)",
  PAR: "Paraguay (PAR)",
  PER: "Peru (PER)",
  PHI: "Philippines (PHI)",
  POL: "Poland (POL)",
  POR: "Portugal (POR)",
  PUR: "Puerto Rico (PUR)",
  QAT: "Qatar (QAT)",
  ROM: "Romania (ROM)",
  RUS: "Russia (RUS)",
  SAM: "Samoa (SAM)",
  SMR: "San Marino (SMR)",
  SEY: "Seychelles (SEY)",
  SIN: "Singapore (SIN)",
  SVK: "Slovak Republic (SVK)",
  SLO: "Slovenia (SLO)",
  SOL: "Solomon Islands (SOL)",
  ESP: "Spain (ESP)",
  SRI: "Sri Lanka (SRI)",
  LCA: "St Lucia (LCA)",
  SWE: "Sweden (SWE)",
  SUI: "Switzerland (SUI)",
  TAH: "Tahiti (TAH)",
  TRI: "Trinidad & Tobago (TRI)",
  TUN: "Tunisia (TUN)",
  TUR: "Turkey (TUR)",
  UKR: "Ukraine (UKR)",
  UAE: "United Arab Emirates (UAE)",
  URU: "Uruguay (URU)",
  ISV: "US Virgin Islands (ISV)",
  VEN: "Venezuela (VEN)",
  YUG: "Yugoslavia (YUG)",
  ZIM: "Zimbabwe (ZIM)",
};
